<?php
/**
 * @file
 * tf_views_testview_features.views_default.inc
 */

/**
 * Implementation of hook_views_default_views().
 */
function tf_views_testview_features_views_default_views() {
  $export = array();

  $view = new view;
  $view->name = 'testview';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'testview';
  $view->core = 7;
  $view->api_version = '3.0-alpha1';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'testview';
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 1;
  /* Field: Content: coretext */
  $handler->display->display_options['fields']['field_coretext']['id'] = 'field_coretext';
  $handler->display->display_options['fields']['field_coretext']['table'] = 'field_data_field_coretext';
  $handler->display->display_options['fields']['field_coretext']['field'] = 'field_coretext';
  $handler->display->display_options['fields']['field_coretext']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_coretext']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_coretext']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_coretext']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_coretext']['element_label_colon'] = 1;
  $handler->display->display_options['fields']['field_coretext']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_coretext']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_coretext']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_coretext']['group_rows'] = 1;
  $handler->display->display_options['fields']['field_coretext']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_coretext']['delta_reversed'] = 0;
  $handler->display->display_options['fields']['field_coretext']['field_api_classes'] = 0;
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 0;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'testcontent' => 'testcontent',
  );

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'testview';
  $handler->display->display_options['menu']['type'] = 'normal';
  $handler->display->display_options['menu']['title'] = 'testview';
  $handler->display->display_options['menu']['name'] = 'features';

  /* Display: Block */
  $handler = $view->new_display('block', 'Block', 'block_1');
  $handler->display->display_options['block_description'] = 'testviewcontent';
  $translatables['testview'] = array(
    t('Master'),
    t('testview'),
    t('more'),
    t('Apply'),
    t('Reset'),
    t('Sort by'),
    t('Asc'),
    t('Desc'),
    t('Items per page'),
    t('- All -'),
    t('Offset'),
    t('coretext'),
    t('Page'),
    t('Block'),
    t('testviewcontent'),
  );
  $export['testview'] = $view;

  return $export;
}
